kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /apache
            backend:
              service:
                name: apache-service
                port:
                  number: 81
          - pathType: Prefix
            path: /nginx
            backend:
              service:
                name: nginx-service
                port:
                  number: 80